name: pull_request

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - master

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - name: Run Tests
        run: go test -cover ./...
